package pdf

// Standard encodings
var (
	WinAnsiEncoding = []string{
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quotesingle",
		"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
		"zero", "one", "two", "three", "four", "five", "six", "seven",
		"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
		"at", "A", "B", "C", "D", "E", "F", "G",
		"H", "I", "J", "K", "L", "M", "N", "O",
		"P", "Q", "R", "S", "T", "U", "V", "W",
		"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
		"grave", "a", "b", "c", "d", "e", "f", "g",
		"h", "i", "j", "k", "l", "m", "n", "o",
		"p", "q", "r", "s", "t", "u", "v", "w",
		"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", "",
		"Euro", "", "quotesinglbase", "florin", "quotedblbase", "ellipsis", "dagger", "daggerdbl",
		"circumflex", "perthousand", "Scaron", "guilsinglleft", "OE", "", "Zcaron", "",
		"", "quoteleft", "quoteright", "quotedblleft", "quotedblright", "bullet", "endash", "emdash",
		"tilde", "trademark", "scaron", "guilsinglright", "oe", "", "zcaron", "Ydieresis",
		"space", "exclamdown", "cent", "sterling", "currency", "yen", "brokenbar", "section",
		"dieresis", "copyright", "ordfeminine", "guillemotleft", "logicalnot", "hyphen", "registered", "macron",
		"degree", "plusminus", "twosuperior", "threesuperior", "acute", "mu", "paragraph", "periodcentered",
		"cedilla", "onesuperior", "ordmasculine", "guillemotright", "onequarter", "onehalf", "threequarters", "questiondown",
		"Agrave", "Aacute", "Acircumflex", "Atilde", "Adieresis", "Aring", "AE", "Ccedilla",
		"Egrave", "Eacute", "Ecircumflex", "Edieresis", "Igrave", "Iacute", "Icircumflex", "Idieresis",
		"Eth", "Ntilde", "Ograve", "Oacute", "Ocircumflex", "Otilde", "Odieresis", "multiply",
		"Oslash", "Ugrave", "Uacute", "Ucircumflex", "Udieresis", "Yacute", "Thorn", "germandbls",
		"agrave", "aacute", "acircumflex", "atilde", "adieresis", "aring", "ae", "ccedilla",
		"egrave", "eacute", "ecircumflex", "edieresis", "igrave", "iacute", "icircumflex", "idieresis",
		"eth", "ntilde", "ograve", "oacute", "ocircumflex", "otilde", "odieresis", "divide",
		"oslash", "ugrave", "uacute", "ucircumflex", "udieresis", "yacute", "thorn", "ydieresis",
	}

	MacRomanEncoding = []string{
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quotesingle",
		"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
		"zero", "one", "two", "three", "four", "five", "six", "seven",
		"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
		"at", "A", "B", "C", "D", "E", "F", "G",
		"H", "I", "J", "K", "L", "M", "N", "O",
		"P", "Q", "R", "S", "T", "U", "V", "W",
		"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
		"grave", "a", "b", "c", "d", "e", "f", "g",
		"h", "i", "j", "k", "l", "m", "n", "o",
		"p", "q", "r", "s", "t", "u", "v", "w",
		"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", "",
		"Adieresis", "Aring", "Ccedilla", "Eacute", "Ntilde", "Odieresis", "Udieresis", "aacute",
		"agrave", "acircumflex", "adieresis", "atilde", "aring", "ccedilla", "eacute", "egrave",
		"ecircumflex", "edieresis", "iacute", "igrave", "icircumflex", "idieresis", "ntilde", "oacute",
		"ograve", "ocircumflex", "odieresis", "otilde", "uacute", "ugrave", "ucircumflex", "udieresis",
		"dagger", "degree", "cent", "sterling", "section", "bullet", "paragraph", "germandbls",
		"registered", "copyright", "trademark", "acute", "dieresis", "notequal", "AE", "Oslash",
		"infinity", "plusminus", "lessequal", "greaterequal", "yen", "mu", "partialdiff", "summation",
		"product", "pi", "integral", "ordfeminine", "ordmasculine", "Omega", "ae", "oslash",
		"questiondown", "exclamdown", "logicalnot", "radical", "florin", "approxequal", "Delta", "guillemotleft",
		"guillemotright", "ellipsis", "nonbreakingspace", "Agrave", "Atilde", "Otilde", "OE", "oe",
		"endash", "emdash", "quotedblleft", "quotedblright", "quoteleft", "quoteright", "divide", "lozenge",
		"ydieresis", "Ydieresis", "fraction", "currency", "guilsinglleft", "guilsinglright", "fi", "fl",
		"daggerdbl", "periodcentered", "quotesinglbase", "quotedblbase", "perthousand", "Acircumflex", "Ecircumflex", "Aacute",
		"Edieresis", "Egrave", "Iacute", "Icircumflex", "Idieresis", "Igrave", "Oacute", "Ocircumflex",
		"apple", "Ograve", "Uacute", "Ucircumflex", "Ugrave", "dotlessi", "circumflex", "tilde",
		"macron", "breve", "dotaccent", "ring", "cedilla", "hungarumlaut", "ogonek", "caron",
	}

	StandardEncoding = []string{
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quoteright",
		"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
		"zero", "one", "two", "three", "four", "five", "six", "seven",
		"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
		"at", "A", "B", "C", "D", "E", "F", "G",
		"H", "I", "J", "K", "L", "M", "N", "O",
		"P", "Q", "R", "S", "T", "U", "V", "W",
		"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
		"quoteleft", "a", "b", "c", "d", "e", "f", "g",
		"h", "i", "j", "k", "l", "m", "n", "o",
		"p", "q", "r", "s", "t", "u", "v", "w",
		"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"exclamdown", "cent", "sterling", "fraction", "yen", "florin", "section", "currency",
		"quotesingle", "quotedblleft", "guillemotleft", "guilsinglleft", "guilsinglright", "fi", "fl", "",
		"endash", "dagger", "daggerdbl", "periodcentered", "", "paragraph", "bullet", "quotesinglbase",
		"quotedblbase", "quotedblright", "guillemotright", "ellipsis", "perthousand", "", "questiondown", "",
		"", "grave", "acute", "circumflex", "tilde", "macron", "breve", "dotaccent",
		"dieresis", "", "ring", "cedilla", "", "hungarumlaut", "ogonek", "caron",
		"emdash", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "AE", "", "ordfeminine", "", "", "", "", "Lslash", "Oslash", "OE", "ordmasculine",
		"", "", "", "", "", "ae", "", "", "", "dotlessi", "", "", "lslash", "oslash", "oe", "germandbls",
		"", "", "", "",
	}
)

// GlyphToUnicode maps glyph names to Unicode strings
var GlyphToUnicode = map[string]string{
	"space":          " ",
	"exclam":         "!",
	"quotedbl":       "\"",
	"numbersign":     "#",
	"dollar":         "$",
	"percent":        "%",
	"ampersand":      "&",
	"quoteright":     "'",
	"parenleft":      "(",
	"parenright":     ")",
	"asterisk":       "*",
	"plus":           "+",
	"comma":          ",",
	"hyphen":         "-",
	"period":         ".",
	"slash":          "/",
	"zero":           "0",
	"one":            "1",
	"two":            "2",
	"three":          "3",
	"four":           "4",
	"five":           "5",
	"six":            "6",
	"seven":          "7",
	"eight":          "8",
	"nine":           "9",
	"colon":          ":",
	"semicolon":      ";",
	"less":           "<",
	"equal":          "=",
	"greater":        ">",
	"question":       "?",
	"at":             "@",
	"A":              "A",
	"B":              "B",
	"C":              "C",
	"D":              "D",
	"E":              "E",
	"F":              "F",
	"G":              "G",
	"H":              "H",
	"I":              "I",
	"J":              "J",
	"K":              "K",
	"L":              "L",
	"M":              "M",
	"N":              "N",
	"O":              "O",
	"P":              "P",
	"Q":              "Q",
	"R":              "R",
	"S":              "S",
	"T":              "T",
	"U":              "U",
	"V":              "V",
	"W":              "W",
	"X":              "X",
	"Y":              "Y",
	"Z":              "Z",
	"bracketleft":    "[",
	"backslash":      "\\",
	"bracketright":   "]",
	"asciicircum":    "^",
	"underscore":     "_",
	"quoteleft":      "`",
	"a":              "a",
	"b":              "b",
	"c":              "c",
	"d":              "d",
	"e":              "e",
	"f":              "f",
	"g":              "g",
	"h":              "h",
	"i":              "i",
	"j":              "j",
	"k":              "k",
	"l":              "l",
	"m":              "m",
	"n":              "n",
	"o":              "o",
	"p":              "p",
	"q":              "q",
	"r":              "r",
	"s":              "s",
	"t":              "t",
	"u":              "u",
	"v":              "v",
	"w":              "w",
	"x":              "x",
	"y":              "y",
	"z":              "z",
	"braceleft":      "{",
	"bar":            "|",
	"braceright":     "}",
	"asciitilde":     "~",
	"exclamdown":     "¡",
	"cent":           "¢",
	"sterling":       "£",
	"fraction":       "⁄",
	"yen":            "¥",
	"florin":         "ƒ",
	"section":        "§",
	"currency":       "¤",
	"quotesingle":    "'",
	"quotedblleft":   "“",
	"guillemotleft":  "«",
	"guilsinglleft":  "‹",
	"guilsinglright": "›",
	"fi":             "fi",
	"fl":             "fl",
	"endash":         "–",
	"dagger":         "†",
	"daggerdbl":      "‡",
	"periodcentered": "·",
	"paragraph":      "¶",
	"bullet":         "•",
	"quotesinglbase": "‚",
	"quotedblbase":   "„",
	"quotedblright":  "”",
	"guillemotright": "»",
	"ellipsis":       "…",
	"perthousand":    "‰",
	"questiondown":   "¿",
	"grave":          "`",
	"acute":          "´",
	"circumflex":     "^",
	"tilde":          "~",
	"macron":         "¯",
	"breve":          "˘",
	"dotaccent":      "˙",
	"dieresis":       "¨",
	"ring":           "˚",
	"cedilla":        "¸",
	"hungarumlaut":   "˝",
	"ogonek":         "˛",
	"caron":          "ˇ",
	"emdash":         "—",
	"AE":             "Æ",
	"ordfeminine":    "ª",
	"Lslash":         "Ł",
	"Oslash":         "Ø",
	"OE":             "Œ",
	"ordmasculine":   "º",
	"ae":             "æ",
	"dotlessi":       "ı",
	"lslash":         "ł",
	"oslash":         "ø",
	"oe":             "œ",
	"germandbls":     "ß",
	"Euro":           "€",
	"copyright":      "©",
	"registered":     "®",
	"trademark":      "™",
	"degree":         "°",
	"plusminus":      "±",
	"twosuperior":    "²",
	"threesuperior":  "³",
	"mu":             "µ",
	"onesuperior":    "¹",
	"onequarter":     "¼",
	"onehalf":        "½",
	"threequarters":  "¾",
	"Agrave":         "À",
	"Aacute":         "Á",
	"Acircumflex":    "Â",
	"Atilde":         "Ã",
	"Adieresis":      "Ä",
	"Aring":          "Å",
	"Ccedilla":       "Ç",
	"Egrave":         "È",
	"Eacute":         "É",
	"Ecircumflex":    "Ê",
	"Edieresis":      "Ë",
	"Igrave":         "Ì",
	"Iacute":         "Í",
	"Icircumflex":    "Î",
	"Idieresis":      "Ï",
	"Eth":            "Ð",
	"Ntilde":         "Ñ",
	"Ograve":         "Ò",
	"Oacute":         "Ó",
	"Ocircumflex":    "Ô",
	"Otilde":         "Õ",
	"Odieresis":      "Ö",
	"multiply":       "×",
	"Ugrave":         "Ù",
	"Uacute":         "Ú",
	"Ucircumflex":    "Û",
	"Udieresis":      "Ü",
	"Yacute":         "Ý",
	"Thorn":          "Þ",
	"agrave":         "à",
	"aacute":         "á",
	"acircumflex":    "â",
	"atilde":         "ã",
	"adieresis":      "ä",
	"aring":          "å",
	"ccedilla":       "ç",
	"egrave":         "è",
	"eacute":         "é",
	"ecircumflex":    "ê",
	"edieresis":      "ë",
	"igrave":         "ì",
	"iacute":         "í",
	"icircumflex":    "î",
	"idieresis":      "ï",
	"eth":            "ð",
	"ntilde":         "ñ",
	"ograve":         "ò",
	"oacute":         "ó",
	"ocircumflex":    "ô",
	"otilde":         "õ",
	"odieresis":      "ö",
	"divide":         "÷",
	"ugrave":         "ù",
	"uacute":         "ú",
	"ucircumflex":    "û",
	"udieresis":      "ü",
	"yacute":         "ý",
	"thorn":          "þ",
	"ydieresis":      "ÿ",
	"Scaron":         "Š",
	"Zcaron":         "Ž",
	"scaron":         "š",
	"zcaron":         "ž",
	"Ydieresis":      "Ÿ",
	"brokenbar":      "¦",
	"logicalnot":     "¬",
	"infinity":       "∞",
	"lessequal":      "≤",
	"greaterequal":   "≥",
	"partialdiff":    "∂",
	"summation":      "∑",
	"product":        "∏",
	"pi":             "π",
	"integral":       "∫",
	"Omega":          "Ω",
	"radical":        "√",
	"approxequal":    "≈",
	"Delta":          "Δ",
	"lozenge":        "◊",
	"apple":          "",

	// TeX Glyphs (Computer Modern)
	// "fi": "fi", // Duplicate
	// "fl": "fl", // Duplicate
	"ff":      "ff",
	"ffi":     "ffi",
	"ffl":     "ffl",
	"alpha":   "α",
	"beta":    "β",
	"gamma":   "γ",
	"delta":   "δ",
	"epsilon": "ϵ",
	"zeta":    "ζ",
	"eta":     "η",
	"theta":   "θ",
	"iota":    "ι",
	"kappa":   "κ",
	"lambda":  "λ",
	// "mu": "μ", // Duplicate
	"nu": "ν",
	"xi": "ξ",
	// "pi": "π", // Duplicate
	"rho":     "ρ",
	"sigma":   "σ",
	"tau":     "τ",
	"upsilon": "υ",
	"phi":     "ϕ",
	"chi":     "χ",
	"psi":     "ψ",
	"omega":   "ω",
	"Gamma":   "Γ",
	// "Delta": "Δ", // Duplicate
	"Theta":   "Θ",
	"Lambda":  "Λ",
	"Xi":      "Ξ",
	"Pi":      "Π",
	"Sigma":   "Σ",
	"Upsilon": "Υ",
	"Phi":     "Φ",
	"Psi":     "Ψ",
	// "Omega": "Ω", // Duplicate
	"phi1":             "φ", // varphi
	"summationdisplay": "∑",
	"parenleftbig":     "(",
	"parenrightbig":    ")",
	"parenleftbigg":    "(",
	"parenrightbigg":   ")",
	"braceleftBigg":    "{",
	"bracerightBigg":   "}",

	// Extended Adobe Glyph List (AGL)
	// Additional mathematical symbols
	"minus":           "−",
	"dotmath":         "⋅",
	"emptyset":        "∅",
	"element":         "∈",
	"notelement":      "∉",
	"suchthat":        "∋",
	"notsuchthat":     "∌",
	"subset":          "⊂",
	"superset":        "⊃",
	"notsubset":       "⊄",
	"subseteql":       "⊆",
	"superseteql":     "⊇",
	"circleplus":      "⊕",
	"circlemultiply":  "⊗",
	"perpendicular":   "⊥",
	"proportional":    "∝",
	"angle":           "∠",
	"existential":     "∃",
	"universal":       "∀",
	"arrowleft":       "←",
	"arrowright":      "→",
	"arrowup":         "↑",
	"arrowdown":       "↓",
	"arrowboth":       "↔",
	"arrowdblup":      "⇑",
	"arrowdbldown":    "⇓",
	"arrowdblleft":    "⇐",
	"arrowdblright":   "⇒",
	"arrowdblboth":    "⇔",
	"congruent":       "≅",
	"similar":         "∼",
	"notequal":        "≠",
	"equivalence":     "≡",
	"lessorequal":     "≤",
	"greaterorequal":  "≥",
	"much less":       "≪",
	"muchgreater":     "≫",
	"therefore":       "∴",
	"because":         "∵",
	"nabla":           "∇",
	"gradient":        "∇",
	"laplacian":       "∇",
	"aleph":           "ℵ",
	"weierstrass":     "℘",
	"Rfractur":        "ℜ",
	"Ifractur":        "ℑ",
	"hbar":            "ℏ",
	"prime":           "′",
	"minute":          "′",
	"second":          "″",
	"dblprime":        "″",
	"dotlessj":        "ȷ",
	"angbracketleft":  "⟨",
	"angbracketright": "⟩",

	// Additional Greek variants
	"varepsilon": "ε",
	"vartheta":   "ϑ",
	"varpi":      "ϖ",
	"varrho":     "ϱ",
	"varsigma":   "ς",
	"varphi":     "φ",
	"epsilon1":   "ε",
	"theta1":     "ϑ",
	"omega1":     "ϖ",
	"rho1":       "ϱ",
	"sigma1":     "ς",
	"uni03D5":    "ϕ",

	// Accented characters from AGL
	"Abreve":        "Ă",
	"abreve":        "ă",
	"Amacron":       "Ā",
	"amacron":       "ā",
	"Aogonek":       "Ą",
	"aogonek":       "ą",
	"Cacute":        "Ć",
	"cacute":        "ć",
	"Ccaron":        "Č",
	"ccaron":        "č",
	"Ccircumflex":   "Ĉ",
	"ccircumflex":   "ĉ",
	"Cdotaccent":    "Ċ",
	"cdotaccent":    "ċ",
	"Dcaron":        "Ď",
	"dcaron":        "ď",
	"Dcroat":        "Đ",
	"dcroat":        "đ",
	"Emacron":       "Ē",
	"emacron":       "ē",
	"Ebreve":        "Ĕ",
	"ebreve":        "ĕ",
	"Edotaccent":    "Ė",
	"edotaccent":    "ė",
	"Eogonek":       "Ę",
	"eogonek":       "ę",
	"Ecaron":        "Ě",
	"ecaron":        "ě",
	"Gbreve":        "Ğ",
	"gbreve":        "ğ",
	"Gcircumflex":   "Ĝ",
	"gcircumflex":   "ĝ",
	"Gcommaaccent":  "Ģ",
	"gcommaaccent":  "ģ",
	"Gdotaccent":    "Ġ",
	"gdotaccent":    "ġ",
	"Hbar":          "Ħ",
	"hbarsmall":     "ħ",
	"Hcircumflex":   "Ĥ",
	"hcircumflex":   "ĥ",
	"Imacron":       "Ī",
	"imacron":       "ī",
	"Ibreve":        "Ĭ",
	"ibreve":        "ĭ",
	"Iogonek":       "Į",
	"iogonek":       "į",
	"Itilde":        "Ĩ",
	"itilde":        "ĩ",
	"Idotaccent":    "İ",
	"Jcircumflex":   "Ĵ",
	"jcircumflex":   "ĵ",
	"Kcommaaccent":  "Ķ",
	"kcommaaccent":  "ķ",
	"kgreenlandic":  "ĸ",
	"Lacute":        "Ĺ",
	"lacute":        "ĺ",
	"Lcaron":        "Ľ",
	"lcaron":        "ľ",
	"Lcommaaccent":  "Ļ",
	"lcommaaccent":  "ļ",
	"Ldot":          "Ŀ",
	"ldot":          "ŀ",
	"Nacute":        "Ń",
	"nacute":        "ń",
	"Ncaron":        "Ň",
	"ncaron":        "ň",
	"Ncommaaccent":  "Ņ",
	"ncommaaccent":  "ņ",
	"napostrophe":   "ŉ",
	"Eng":           "Ŋ",
	"eng":           "ŋ",
	"Omacron":       "Ō",
	"omacron":       "ō",
	"Obreve":        "Ŏ",
	"obreve":        "ŏ",
	"Ohungarumlaut": "Ő",
	"ohungarumlaut": "ő",
	"Racute":        "Ŕ",
	"racute":        "ŕ",
	"Rcaron":        "Ř",
	"rcaron":        "ř",
	"Rcommaaccent":  "Ŗ",
	"rcommaaccent":  "ŗ",
	"Sacute":        "Ś",
	"sacute":        "ś",
	"Scircumflex":   "Ŝ",
	"scircumflex":   "ŝ",
	"Scedilla":      "Ş",
	"scedilla":      "ş",
	"Tbar":          "Ŧ",
	"tbar":          "ŧ",
	"Tcaron":        "Ť",
	"tcaron":        "ť",
	"Tcommaaccent":  "Ţ",
	"tcommaaccent":  "ţ",
	"Umacron":       "Ū",
	"umacron":       "ū",
	"Ubreve":        "Ŭ",
	"ubreve":        "ŭ",
	"Uring":         "Ů",
	"uring":         "ů",
	"Uhungarumlaut": "Ű",
	"uhungarumlaut": "ű",
	"Uogonek":       "Ų",
	"uogonek":       "ų",
	"Utilde":        "Ũ",
	"utilde":        "ũ",
	"Wcircumflex":   "Ŵ",
	"wcircumflex":   "ŵ",
	"Ycircumflex":   "Ŷ",
	"ycircumflex":   "ŷ",
	"Zacute":        "Ź",
	"zacute":        "ź",
	"Zdotaccent":    "Ż",
	"zdotaccent":    "ż",

	// Typographic symbols
	"openbullet":     "◦",
	"triangleup":     "▲",
	"triangledown":   "▼",
	"triangleleft":   "◀",
	"triangleright":  "▶",
	"triagup":        "▲",
	"triagdn":        "▼",
	"triaglf":        "◀",
	"triagrt":        "▶",
	"blacksquare":    "■",
	"whitesquare":    "□",
	"blackcircle":    "●",
	"whitecircle":    "○",
	"filledbox":      "■",
	"openbox":        "□",
	"H18533":         "●",
	"H18543":         "■",
	"H18551":         "○",
	"H17745":         "◆",
	"star":           "★",
	"blackstar":      "★",
	"whitestar":      "☆",
	"heart":          "♥",
	"diamond":        "♦",
	"club":           "♣",
	"spade":          "♠",
	"musicalnote":    "♪",
	"musicalnotedbl": "♫",
	"female":         "♀",
	"male":           "♂",
	"checkmark":      "✓",
	"crossmark":      "✗",
	"maltesecross":   "✠",

	// Currency symbols
	"afii57636":     "₤",
	"peseta":        "₧",
	"dong":          "₫",
	"won":           "₩",
	"lira":          "₤",
	"naira":         "₦",
	"peso":          "₱",
	"rupee":         "₹",
	"sheqel":        "₪",
	"baht":          "฿",
	"colonmonetary": "₡",

	// Spaces
	"nbspace":          " ",
	"nonbreakingspace": " ",
	"thinspace":        " ",
	"hairspace":        " ",
	"enspace":          " ",
	"emspace":          " ",
	"figurespace":      " ",
	"zerowidthspace":   "\u200b",

	// Dashes and hyphens
	"softhyphen":    "\u00ad",
	"figureminus":   "−",
	"horizontalbar": "―",
	"afii00208":     "—",

	// Additional quotation marks
	"quotereversed": "‛",

	// TeX math sizing delimiters
	"parenleftBig":    "(",
	"parenrightBig":   ")",
	"bracketleftBig":  "[",
	"bracketrightBig": "]",
	"braceleftBig":    "{",
	"bracerightBig":   "}",
	"parenleftEx":     "(",
	"parenrightEx":    ")",
	"bracketleftEx":   "[",
	"bracketrightEx":  "]",
	"braceleftMid":    "{",
	"bracerightMid":   "}",
	"integraltp":      "⌠",
	"integralbt":      "⌡",
	"integralex":      "⎮",
	"radicalex":       "√",
	"radicalBig":      "√",
	"radicalBigg":     "√",
	"radicalbig":      "√",
	"radicalbigg":     "√",

	// Symbol font characters
	"copyrightserif": "©",
	"registerserif":  "®",
	"trademarkserif": "™",

	// Miscellaneous symbols
	"estimated":      "℮",
	"numero":         "№",
	"servicemark":    "℠",
	"carriagereturn": "↵",
	"arrowvertex":    "│",
	"arrowhorizex":   "─",
	"shade":          "░",
	"ltshade":        "░",
	"dkshade":        "▓",
	"block":          "█",

	// Additional ligatures
	"IJ": "Ĳ",
	"ij": "ĳ",

	// Combining characters as standalone (for some fonts)
	"gravecomb":     "̀",
	"acutecomb":     "́",
	"tildecomb":     "̃",
	"hookabovecomb": "̉",
	"dotbelowcomb":  "̣",
	"dieresiscomb":  "̈",
	"ringcomb":      "̊",
	"cedillacomb":   "̧",
}
